qa_300_dual_render:
  ast_similarity: 98.3%
  quorum_decision: pass
  route_to: none
  semantic_distance: 0.0174
  threshold: 0.03
  files_compared:
    sonnet_a: test_samples/sonnet_a_output.py
    sonnet_b: test_samples/sonnet_b_output.py
  metrics:
    token_similarity: 0.9783
    structure_similarity: 0.9952
    execution_time_ms: 16794.55
  timestamp: '2025-06-11T09:57:01.186236'
  rollback: qa-revert
