version: "3.9"

services:
  api-canary:
    image: python:3.11-slim  # placeholder - replace with registry/swarm/api:v2.6.0
    env_file: ["env/prod.env", "env/canary.env"]
    ports: []                     # internal only
    command: ["python", "-c", "import time; print('Canary API service placeholder running...'); [time.sleep(60) for _ in iter(int, 1)]"]
    volumes:
      - faiss_memory:/data/faiss
      - swarm_logs:/var/log/swarm
    deploy:
      resources: 
        limits: { memory: 3g }
      restart_policy:
        condition: always
    labels:
      - traefik.enable=true
      - traefik.http.services.council-canary.loadbalancer.server.port=9000
      - traefik.http.services.council-canary.loadbalancer.healthcheck.path=/health
      - traefik.http.services.council-canary.loadbalancer.healthcheck.interval=30s
      - traefik.http.routers.api-canary.rule=Host(`api.swarm.local`) && Headers(`X-Canary`, `true`)
      - traefik.http.routers.api-canary.service=council-canary
      - traefik.docker.network=swarm_network
    healthcheck: 
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 30s
      timeout: 10s
      retries: 3 