version: "3.9"

services:
  pushgw:
    image: prom/pushgateway:latest
    ports: ["9091:9091"]
    deploy:
      resources:
        limits: { memory: 256m }
      restart_policy:
        condition: on-failure
    volumes:
      - pushgw_data:/data
    command:
      - '--web.listen-address=:9091'
      - '--persistence.file=/data/pushgateway.db'
      - '--persistence.interval=5m'
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9091/-/healthy"]
      interval: 30s
      timeout: 5s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  pushgw_data: 