groups:
  - name: reward_model_alerts
    rules:
      - alert: RewardLowAcc
        expr: reward_val_accuracy < 0.65
        for: 5m
        labels:
          severity: warn
          component: reward-model
          team: "swarm-ops"
        annotations:
          summary: "🧠 Reward model validation accuracy critically low"
          description: "Reward model validation accuracy is {{ $value | humanizePercentage }} (<65%). This may indicate insufficient training data or model degradation."
          runbook_url: "https://docs.swarm.ai/runbook/reward-model-low-accuracy"

      - alert: RewardTrainingFailed
        expr: absent(reward_val_accuracy) or increase(reward_val_accuracy[24h]) == 0
        for: 6h
        labels:
          severity: critical
          component: reward-model
          team: "swarm-ops"
        annotations:
          summary: "🚨 Reward model training pipeline failed"
          description: "No reward model metrics received in 6+ hours. Check nightly training cron job."
          runbook_url: "https://docs.swarm.ai/runbook/reward-training-failure"

      - alert: RewardDataInsufficient  
        expr: absent(reward_val_accuracy) and time() % 86400 > 7200 and time() % 86400 < 10800
        for: 30m
        labels:
          severity: warn
          component: reward-model
          team: "swarm-ops"
        annotations:
          summary: "📊 Insufficient preference data for training"
          description: "Reward model training likely skipped due to < 50 preference pairs. Check feedback collection."
          runbook_url: "https://docs.swarm.ai/runbook/reward-data-collection"

- name: swarm.rules
  rules:
    - alert: HighVRAM
      expr: swarm_vram_used_bytes{gpu="0"} > 0.9 * 12 * 1024 * 1024 * 1024
      for: 1m
      labels: 
        severity: page
      annotations: 
        summary: "GPU VRAM >90%"
        description: "GPU 0 VRAM usage is {{ $value | humanizeBytes }} (>90% of 12GB)"
        
    - alert: RouterLatencyP95
      expr: histogram_quantile(0.95, sum(rate(swarm_router_request_latency_bucket[2m])) by (le)) > 0.5
      for: 2m
      labels: 
        severity: page
      annotations: 
        summary: "p95 latency >500ms"
        description: "Router p95 latency is {{ $value | humanizeDuration }} (>500ms threshold)"
        
    - alert: CUDAFragmentation
      expr: increase(swarm_cuda_fragmentation_events_total[5m]) > 0
      labels: 
        severity: page
      annotations: 
        summary: "CUDA allocator fragmentation detected"
        description: "{{ $value }} CUDA fragmentation events in last 5m - memory allocator stress"

- name: swarm.infrastructure
  rules:
    # Additional safety nets for production
    - alert: HighErrorRate
      expr: rate(swarm_router_errors_total[5m]) > 0.1
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "High error rate detected"
        description: "Error rate is {{ $value | humanizePercentage }} (>10% threshold)"
        
    - alert: ServiceDown
      expr: up{job="swarm-api"} == 0
      for: 30s
      labels:
        severity: critical
      annotations:
        summary: "Swarm API service down"
        description: "Main API service has been down for >30s"
        
    - alert: DiskSpaceLow
      expr: (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) * 100 < 15
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "Low disk space"
        description: "Filesystem has less than 15% space remaining"

- name: template_detection
  rules:
    - alert: Phi3TemplateAnswer
      expr: increase(phi3_template_total[2m]) > 0
      for: 1m
      labels:
        severity: "warning"
        team: "trinity"
      annotations:
        summary: "Phi3 template response detected"
        description: "Phi3 returned boilerplate template response - system_prompt not working"
        runbook_url: "https://wiki.trinity.local/alerts/phi3-template" 