global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'api_canary'
    static_configs:
      - targets: ['host.docker.internal:8001']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'pushgateway'
    static_configs:
      - targets: ['host.docker.internal:9091']
    scrape_interval: 15s

  - job_name: 'redis'
    static_configs:
      - targets: ['host.docker.internal:9121']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 5s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  - job_name: 'trainer'
    static_configs:
      - targets: ['trainer:8080']
    scrape_interval: 60s 