global:
  # Global AlertManager configuration
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@swarm.ai'
  smtp_auth_username: 'alertmanager@swarm.ai'
  smtp_auth_password: 'test-password'  # Test password for demo

# =============================================================================
# 🔀 ROUTING - Send alerts to appropriate channels
# =============================================================================
route:
  # Default receiver for all alerts
  receiver: 'swarm-ops-default'
  group_by: ['alertname', 'environment', 'component']
  group_wait: 30s          # Wait 30s to group similar alerts
  group_interval: 5m       # Send group updates every 5m
  repeat_interval: 4h      # Repeat critical alerts every 4h

  routes:
    # 🧪 TEST ALERTS - Silent by default
    - match:
        severity: test
      receiver: 'test-silent'
      group_wait: 0s
      group_interval: 1m
      repeat_interval: 24h

    # 🚨 PAGE LEVEL - Immediate escalation
    - match:
        severity: page
      receiver: 'swarm-ops-pager'
      group_wait: 0s         # Immediate paging
      group_interval: 1m     # Quick updates
      repeat_interval: 30m   # Repeat every 30m until resolved

    # 🔥 CRITICAL ALERTS - Slack + Email
    - match:
        severity: critical
      receiver: 'swarm-ops-critical'
      group_wait: 10s
      group_interval: 2m
      repeat_interval: 1h

    # ⚠️ WARNING ALERTS - Slack notifications
    - match:
        severity: warning
      receiver: 'swarm-ops-warnings'
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 8h

    # 🐦 CANARY ALERTS - Special handling
    - match:
        component: canary
      receiver: 'canary-alerts'
      group_wait: 5s
      group_interval: 1m
      repeat_interval: 30m

    # 🛡️ SECURITY ALERTS - Immediate security team notification
    - match:
        escalation: security-team
      receiver: 'security-team'
      group_wait: 0s
      group_interval: 30s
      repeat_interval: 15m

# =============================================================================
# 📞 RECEIVERS - Define notification channels
# =============================================================================
receivers:
  # Default receiver
  - name: 'swarm-ops-default'
    webhook_configs:
      - url: 'http://localhost:8000/webhook/slack-ops'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'alertmanager'
            password: 'test'

  # Test alerts - silent logging only
  - name: 'test-silent'
    webhook_configs:
      - url: 'http://localhost:8000/webhook/test-alerts'
        send_resolved: true

  # Page-level alerts - PagerDuty integration
  - name: 'swarm-ops-pager'
    webhook_configs:
      - url: 'http://localhost:8000/webhook/pagerduty'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'pagerduty'
            password: 'test-integration-key'
      - url: 'http://localhost:8000/webhook/slack-incidents'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'slack'
            password: 'incidents-webhook'

  # Critical alerts - Slack + Email
  - name: 'swarm-ops-critical'
    webhook_configs:
      - url: 'http://localhost:8000/webhook/slack-ops'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'slack'
            password: 'ops-webhook'
      - url: 'http://localhost:8000/webhook/email-critical'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'email'
            password: 'swarm-ops@company.com'

  # Warning alerts - Slack only
  - name: 'swarm-ops-warnings'
    webhook_configs:
      - url: 'http://localhost:8000/webhook/slack-ops'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'slack'
            password: 'ops-webhook'

  # Canary-specific alerts
  - name: 'canary-alerts'
    webhook_configs:
      - url: 'http://localhost:8000/webhook/slack-deployments'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'slack'
            password: 'deployments-webhook'

  # Security team alerts
  - name: 'security-team'
    webhook_configs:
      - url: 'http://localhost:8000/webhook/slack-security'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'slack'
            password: 'security-webhook'
      - url: 'http://localhost:8000/webhook/email-security'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'email'
            password: 'security@company.com'

# =============================================================================
# 🔇 INHIBIT RULES - Prevent alert storms
# =============================================================================
inhibit_rules:
  # Inhibit warning if critical is firing for same component
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['environment', 'component']

  # Inhibit critical if emergency/page is firing
  - source_match:
      severity: 'page'
    target_match:
      severity: 'critical'
    equal: ['environment', 'component']

  # During maintenance windows, inhibit non-security alerts
  - source_match:
      alertname: 'MaintenanceWindow'
    target_match_re:
      severity: '^(warning|critical)$'
    equal: ['environment']

# =============================================================================
# 📝 TEMPLATES - Alert message formatting
# =============================================================================
templates:
  - '/etc/alertmanager/templates/*.tmpl' 