global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

scrape_configs:
  # Pushgateway for chaos testing and metrics injection
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']
    scrape_interval: 5s
    metrics_path: '/metrics'

  # Test Metrics Server - VRAM simulation for alert testing
  - job_name: 'test-metrics-server'
    static_configs:
      - targets: ['host.docker.internal:8080']
    scrape_interval: 5s
    metrics_path: '/metrics'

  # Main Council API metrics - VRAM, latency, request counts
  - job_name: 'council-api'
    static_configs:
      - targets: ['council-api:9000']
    scrape_interval: 5s
    metrics_path: '/metrics'

  # Canary Council API metrics - for A/B testing
  - job_name: 'council-api-canary'
    static_configs:
      - targets: ['council-api-canary:9000']
    scrape_interval: 5s
    metrics_path: '/metrics'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance_type
        replacement: canary

  # LoRA Trainer metrics - training costs, success rates
  - job_name: 'lora-trainer'
    static_configs:
      - targets: ['lora-trainer:8080']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # Traefik Load Balancer metrics - traffic distribution
  - job_name: 'traefik'
    static_configs:
      - targets: ['lb-traefik:8080']
    scrape_interval: 15s
    metrics_path: '/metrics'

  # Redis metrics for caching performance
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # AlertManager metrics
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093'] 