# Prometheus Configuration for Trinity Council
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'council-api'
    static_configs:
      - targets: ['host.docker.internal:9000']
    scrape_interval: 10s
    metrics_path: '/metrics'

  - job_name: 'guardian'
    static_configs:
      - targets: ['host.docker.internal:8000']
    scrape_interval: 15s
    metrics_path: '/metrics'

  - job_name: 'tiny-svc'
    static_configs:
      - targets: ['host.docker.internal:8005']
    scrape_interval: 30s
    metrics_path: '/metrics'

  - job_name: 'pushgateway'
    static_configs:
      - targets: ['host.docker.internal:9091']
    scrape_interval: 15s
    metrics_path: '/metrics'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - host.docker.internal:9093 