# Prometheus Configuration for Trinity Council - H1.5 Network Fix
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'council-api'
    static_configs:
      - targets: ['council-api:9000']
    scrape_interval: 10s
    metrics_path: '/metrics'

  - job_name: 'guardian'
    static_configs:
      - targets: ['guardian:9105']
    scrape_interval: 15s
    metrics_path: '/metrics'

  - job_name: 'builder-tiny-svc'
    static_configs:
      - targets: ['tiny-svc:8005']
    scrape_interval: 30s
    metrics_path: '/metrics'

  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']
    scrape_interval: 15s
    metrics_path: '/metrics'

  - job_name: 'textfile-exporter'
    static_configs:
      - targets: ['textfile-exporter:9103']
    scrape_interval: 30s
    metrics_path: '/metrics'

  - job_name: 'agent-heartbeat'
    static_configs:
      - targets: ['agent-heartbeat:9104']
    scrape_interval: 15s
    metrics_path: '/metrics'

  - job_name: 'guide-loader'
    static_configs:
      - targets: ['guide-loader:9108']
    scrape_interval: 15s
    metrics_path: '/metrics'

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s
    metrics_path: '/metrics'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    metrics_path: '/metrics'

  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
    scrape_interval: 30s
    metrics_path: '/metrics'

rule_files:
  - "/etc/prometheus/rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093