global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"
  - "alert_rules.yml"
  - "roundtable.rules.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Traefik Load Balancer metrics
  - job_name: 'traefik'
    static_configs:
      - targets: ['lb-traefik:8080']
    scrape_interval: 15s
    metrics_path: '/metrics'

  # Mock Round Table metrics for dashboard testing
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['host.docker.internal:9091']
    scrape_interval: 15s
    metrics_path: '/metrics'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093 