global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

scrape_configs:
  # AutoGen Council API metrics
  - job_name: 'autogen-council'
    static_configs:
      - targets: ['council:8000']
    scrape_interval: 5s
    metrics_path: '/metrics'

  # Canary deployment metrics  
  - job_name: 'canary-server'
    static_configs:
      - targets: ['canary-server:8000']
    scrape_interval: 5s
    metrics_path: '/metrics'

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # AlertManager metrics
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093'] 